/**
 * Atribuição| =
 * Adição| +
 * Subtração| -
 * Divisão| /
 * Multiplicação| *
 * 
 * Valor operador valor
 * negação      | ! | !false |      True
 * Igual        | == | 3 == 3 |     True
 * diferente    | != | 3 != 3.1 |   True
 * Maior        | >  | 4 > 4 |      True
 * menor        | <  | 4 < 4 |      False
 * Maior Igual  | 4 >= 4 |          True
 * Menor Igual  | 5 <= 5 |          True
 
 */